baseURL = "https://naotou-maohan.github.io/"
languageCode = "zh-cn"
title = "我的博客"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowToc = true

params:
  profileMode:
    enabled: true
    title: "<Hi there>" # optional default will be site title
    subtitle: "通信 | 电子 | 编程 | 学习记录"
    buttons:
      - name: 文章
        url: "posts"
      - name: 关于
        url: "about"
    socialIcons: # optional
        - name: "<我的第一条博客>"
        url: "posts/hello.md"
