baseURL = "https://naotou-maohan.github.io/"
languageCode = "zh-cn"
title = "我的博客"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowToc = true

        
[params.homeInfoParams]
enabled = true
title = "Hi there"
Content = "通信 | 电子 | 编程 | 学习记录"

[[params.homeInfoParams.buttons]]
name = "文章"
url = "posts"

[[params.homeInfoParamse.buttons]]
name = "关于"
url = "about"


